name: Free-RDP

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download LocalXpose
      run: Invoke-WebRequest https://files.localxpose.io/localxpose/windows/localxpose.exe -OutFile localxpose.exe

    - name: Enable RDP
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

    - name: Start LocalXpose Tunnel
      run: .\localxpose.exe tcp --port 3389 --token $Env:LOCALTOKEN
      env:
        LOCALTOKEN: ${{ secrets.LOCALTOKEN }}
